"""Built-in read-only query tools for wiki-style knowledge bases."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import PurePosixPath
from typing import Any, Mapping

from heta_framework.common.stores.object import ObjectStoreProtocol
from heta_framework.common.stores.object.types import join_object_key, validate_object_key
from heta_framework.kb.search.assets import SearchAssetRef
from heta_framework.kb.search.tools import QueryToolContext, QueryToolResult
from heta_framework.kb.search.types import QueryCitation, QueryRequest, QueryResult
from heta_framework.kb.steps.types import ComponentRef, model_ref, store_ref


@dataclass(frozen=True)
class ReadWikiIndexTool:
    """Read the generated wiki index."""

    name: str = "read_wiki_index"
    index_key: str = "wiki/index.md"
    index_key_artifact: str = "wiki_index_key"
    object_store: str | None = None
    max_chars: int | None = None

    @property
    def description(self) -> str:
        return "Read the wiki index generated by BuildWikiPages."

    @property
    def parameters_schema(self) -> Mapping[str, Any]:
        return {
            "type": "object",
            "properties": {},
            "additionalProperties": False,
        }

    @property
    def required_assets(self) -> frozenset[SearchAssetRef]:
        return frozenset()

    @property
    def required_components(self) -> frozenset[ComponentRef]:
        return frozenset({store_ref("objects", self.object_store)})

    async def run(
        self,
        arguments: Mapping[str, Any],
        context: QueryToolContext,
    ) -> QueryToolResult:
        object_store = _require_object_store(
            context.get_component(store_ref("objects", self.object_store))
        )
        key = _artifact_string(
            context,
            self.index_key_artifact,
            default=self.index_key,
        )
        if not await object_store.exists(key):
            return QueryToolResult.error(
                f"error: wiki index does not exist: {key}",
                metadata={"object_key": key, "citable": False},
            )
        text = (await object_store.get(key)).decode("utf-8", errors="replace")
        if not text.strip():
            return QueryToolResult.error(
                f"error: wiki index is empty: {key}",
                metadata={"object_key": key, "citable": False},
            )
        content, truncated = _truncate(
            f"Wiki Index ({key}):\n{text}",
            max_chars=self.max_chars or context.budget.max_tool_result_chars,
        )
        return QueryToolResult(
            content=content,
            metadata={
                "object_key": key,
                "truncated": truncated,
                "citable": False,
            },
        )


@dataclass(frozen=True)
class SearchWikiTool:
    """Search wiki chunks through an existing query engine."""

    name: str = "search_wiki"
    query_mode: str = "wiki_hybrid_search"
    asset_refs: frozenset[SearchAssetRef] = frozenset(
        {
            SearchAssetRef(kind="wiki_chunk_vector_index"),
            SearchAssetRef(kind="wiki_chunk_full_text_index"),
        }
    )
    max_top_k: int = 10
    max_chars: int | None = None
    embedding_model: str | None = None

    @property
    def description(self) -> str:
        return (
            "Search wiki chunks using semantic and lexical retrieval. Returns matching "
            "wiki pages, heading paths, chunk text, scores, and source metadata."
        )

    @property
    def parameters_schema(self) -> Mapping[str, Any]:
        return {
            "type": "object",
            "properties": {
                "query": {"type": "string"},
                "top_k": {"type": "integer", "minimum": 1, "maximum": self.max_top_k},
            },
            "required": ["query"],
            "additionalProperties": False,
        }

    @property
    def required_assets(self) -> frozenset[SearchAssetRef]:
        return self.asset_refs

    @property
    def required_components(self) -> frozenset[ComponentRef]:
        return frozenset({model_ref("embedding", self.embedding_model)})

    async def run(
        self,
        arguments: Mapping[str, Any],
        context: QueryToolContext,
    ) -> QueryToolResult:
        try:
            query = _required_string(arguments, "query")
            top_k = _bounded_top_k(
                arguments.get("top_k"),
                default=context.request.top_k,
                maximum=self.max_top_k,
            )
        except (TypeError, ValueError) as exc:
            return QueryToolResult.error(f"error: {exc}", metadata={"citable": False})
        response = await context.query(
            self.query_mode,
            QueryRequest(
                text=query,
                mode=self.query_mode,
                top_k=top_k,
                filters=context.request.filters,
                options={**context.request.options, "generate_answer": False},
                trace=context.request.trace,
            ),
        )
        content, truncated = _truncate(
            _format_search_results(response.results, query=query, mode=response.mode),
            max_chars=self.max_chars or context.budget.max_tool_result_chars,
        )
        return QueryToolResult(
            content=content,
            results=response.results,
            citations=response.citations,
            metadata={
                "query": query,
                "query_mode": response.mode,
                "top_k": top_k,
                "result_count": len(response.results),
                "truncated": truncated,
                "citable": True,
            },
        )


@dataclass(frozen=True)
class ReadWikiPageTool:
    """Read one generated wiki page."""

    name: str = "read_wiki_page"
    pages_prefix: str = "wiki/pages"
    display_prefix: str = "pages"
    object_store: str | None = None
    max_chars: int | None = None

    @property
    def description(self) -> str:
        return "Read a generated wiki page. Valid paths: pages/*.md or wiki/pages/*.md."

    @property
    def parameters_schema(self) -> Mapping[str, Any]:
        return {
            "type": "object",
            "properties": {"path": {"type": "string"}},
            "required": ["path"],
            "additionalProperties": False,
        }

    @property
    def required_assets(self) -> frozenset[SearchAssetRef]:
        return frozenset()

    @property
    def required_components(self) -> frozenset[ComponentRef]:
        return frozenset({store_ref("objects", self.object_store)})

    async def run(
        self,
        arguments: Mapping[str, Any],
        context: QueryToolContext,
    ) -> QueryToolResult:
        object_store = _require_object_store(
            context.get_component(store_ref("objects", self.object_store))
        )
        try:
            path = _required_string(arguments, "path")
            page = _normalize_wiki_page_path(
                path,
                pages_prefix=self.pages_prefix,
                display_prefix=self.display_prefix,
            )
        except ValueError as exc:
            return QueryToolResult.error(f"error: {exc}", metadata={"citable": False})

        if not await object_store.exists(page.object_key):
            return QueryToolResult.error(
                f"error: wiki page does not exist: {page.display_path}",
                metadata={
                    "path": page.display_path,
                    "object_key": page.object_key,
                    "citable": False,
                },
            )
        text = (await object_store.get(page.object_key)).decode("utf-8", errors="replace")
        if not text.strip():
            return QueryToolResult.error(
                f"error: wiki page is empty: {page.display_path}",
                metadata={
                    "path": page.display_path,
                    "object_key": page.object_key,
                    "citable": False,
                },
            )
        content, truncated = _truncate(
            f"Wiki Page: {page.display_path}\nObject Key: {page.object_key}\n\n{text}",
            max_chars=self.max_chars or context.budget.max_tool_result_chars,
        )
        result = QueryResult(
            id=page.object_key,
            text=text,
            kind="wiki_page",
            source=_wiki_source(page),
            metadata={
                "path": page.display_path,
                "object_key": page.object_key,
                "citable": True,
                "truncated": truncated,
            },
        )
        citation = QueryCitation(
            id=_citation_id(page.object_key),
            result_id=result.id,
            source=result.source,
            text=result.text,
            metadata={"result_kind": result.kind},
        )
        return QueryToolResult(
            content=content,
            results=(result,),
            citations=(citation,),
            metadata={
                "path": page.display_path,
                "object_key": page.object_key,
                "truncated": truncated,
                "citable": True,
            },
        )


@dataclass(frozen=True)
class ReadRawObjectTool:
    """Read one raw source object referenced by wiki pages."""

    name: str = "read_raw_object"
    raw_prefix: str = "raw"
    object_store: str | None = None
    max_chars: int = 16_000

    @property
    def description(self) -> str:
        return (
            "Read an original raw object referenced by a wiki page. Raw content is "
            "supporting context and should not be used as a final citation."
        )

    @property
    def parameters_schema(self) -> Mapping[str, Any]:
        return {
            "type": "object",
            "properties": {"path": {"type": "string"}},
            "required": ["path"],
            "additionalProperties": False,
        }

    @property
    def required_assets(self) -> frozenset[SearchAssetRef]:
        return frozenset()

    @property
    def required_components(self) -> frozenset[ComponentRef]:
        return frozenset({store_ref("objects", self.object_store)})

    async def run(
        self,
        arguments: Mapping[str, Any],
        context: QueryToolContext,
    ) -> QueryToolResult:
        object_store = _require_object_store(
            context.get_component(store_ref("objects", self.object_store))
        )
        try:
            path = _required_string(arguments, "path")
            object_key = _normalize_raw_object_key(path, raw_prefix=self.raw_prefix)
        except ValueError as exc:
            return QueryToolResult.error(f"error: {exc}", metadata={"citable": False})

        if not await object_store.exists(object_key):
            return QueryToolResult.error(
                f"error: raw object does not exist: {object_key}",
                metadata={"object_key": object_key, "citable": False},
            )
        text = (await object_store.get(object_key)).decode("utf-8", errors="replace")
        if not text.strip():
            return QueryToolResult.error(
                f"error: raw object is empty: {object_key}",
                metadata={"object_key": object_key, "citable": False},
            )
        content, truncated = _truncate(
            f"Raw Object: {object_key}\n\n{text}",
            max_chars=min(self.max_chars, context.budget.max_tool_result_chars),
        )
        return QueryToolResult(
            content=content,
            metadata={
                "object_key": object_key,
                "truncated": truncated,
                "citable": False,
                "raw_context_only": True,
            },
        )


@dataclass(frozen=True)
class _WikiPagePath:
    display_path: str
    object_key: str


def _artifact_string(
    context: QueryToolContext,
    artifact_name: str,
    *,
    default: str,
) -> str:
    value = context.query_context.run_record.artifacts.get(artifact_name)
    if isinstance(value, str) and value.strip():
        return validate_object_key(value)
    return validate_object_key(default)


def _normalize_wiki_page_path(
    path: str,
    *,
    pages_prefix: str,
    display_prefix: str,
) -> _WikiPagePath:
    normalized = path.replace("\\", "/").strip().strip("/")
    if normalized == "":
        raise ValueError("path must not be empty")
    pages_prefix = pages_prefix.strip("/")
    display_prefix = display_prefix.strip("/")
    if normalized.startswith(f"{pages_prefix}/"):
        relative = normalized[len(pages_prefix) + 1 :]
    elif normalized.startswith(f"{display_prefix}/"):
        relative = normalized[len(display_prefix) + 1 :]
    else:
        raise ValueError(
            f"path must start with {display_prefix}/ or {pages_prefix}/, got: {path!r}"
        )
    relative = validate_object_key(relative)
    if PurePosixPath(relative).suffix.lower() != ".md":
        raise ValueError("path must reference a markdown wiki page")
    return _WikiPagePath(
        display_path=join_object_key(display_prefix, relative),
        object_key=join_object_key(pages_prefix, relative),
    )


def _normalize_raw_object_key(path: str, *, raw_prefix: str) -> str:
    normalized = path.replace("\\", "/").strip().strip("/")
    if normalized == "":
        raise ValueError("path must not be empty")
    raw_prefix = raw_prefix.strip("/")
    if raw_prefix and normalized.startswith(f"{raw_prefix}/"):
        relative = normalized[len(raw_prefix) + 1 :]
    elif raw_prefix and f"/{raw_prefix}/" in normalized:
        relative = normalized.split(f"/{raw_prefix}/", 1)[1]
    else:
        relative = normalized
    relative = validate_object_key(relative)
    return join_object_key(raw_prefix, relative) if raw_prefix else relative


def _required_string(arguments: Mapping[str, Any], key: str) -> str:
    value = arguments.get(key)
    if not isinstance(value, str) or value.strip() == "":
        raise ValueError(f"{key} must be a non-empty string")
    return value.strip()


def _bounded_top_k(value: object, *, default: int, maximum: int) -> int:
    if value is None:
        top_k = default
    elif isinstance(value, bool):
        raise ValueError("top_k must be an integer")
    else:
        top_k = int(value)
    if top_k <= 0:
        raise ValueError("top_k must be greater than zero")
    return min(top_k, maximum)


def _format_search_results(
    results: tuple[QueryResult, ...],
    *,
    query: str,
    mode: str,
) -> str:
    if not results:
        return f"Search mode: {mode}\nQuery: {query}\nResults: None."
    parts = [f"Search mode: {mode}", f"Query: {query}", "Results:"]
    for index, result in enumerate(results, start=1):
        source_key = result.source.get("object_key") or result.metadata.get("source_key")
        heading = result.metadata.get("heading_path") or result.metadata.get("heading")
        score = "" if result.score is None else f"{result.score:.3f}"
        parts.append(
            "\n".join(
                (
                    f"[{index}]",
                    f"id: {result.id}",
                    f"kind: {result.kind}",
                    f"score: {score}",
                    f"source: {source_key or ''}",
                    f"heading: {heading or ''}",
                    "content:",
                    result.text,
                )
            )
        )
    return "\n\n".join(parts)


def _wiki_source(page: _WikiPagePath) -> dict[str, Any]:
    return {
        "object_key": page.object_key,
        "object_name": PurePosixPath(page.object_key).name,
        "object_type": "wiki",
        "path": page.display_path,
    }


def _citation_id(value: str) -> str:
    slug = "".join(char if char.isalnum() else "_" for char in value.lower())
    slug = "_".join(part for part in slug.split("_") if part)
    return f"citation_{slug[:64] or 'wiki_page'}"


def _truncate(text: str, *, max_chars: int) -> tuple[str, bool]:
    if len(text) <= max_chars:
        return text, False
    return text[:max_chars].rstrip() + "\n\n[truncated]", True


def _require_object_store(component: object) -> ObjectStoreProtocol:
    if not isinstance(component, ObjectStoreProtocol):
        raise TypeError("stores.objects must satisfy ObjectStoreProtocol")
    return component
