"""Clusterable in-memory graph store implementation."""

from __future__ import annotations

from collections import defaultdict
from typing import Any

from heta_framework.common.stores.graph.memory import InMemoryGraphStore
from heta_framework.common.stores.graph.types import GraphEdge, GraphNode


class ClusterableInMemoryGraphStore(InMemoryGraphStore):
    """In-memory graph store with community clustering support."""

    def __init__(self) -> None:
        super().__init__()
        self._communities: dict[str, dict[str, Any]] = {}

    async def clustering(self, algorithm: str) -> None:
        """Run graph clustering and persist cluster metadata in the store."""
        if algorithm == "connected_components":
            self._communities = _connected_component_schema(
                list(self.nodes.values()),
                list(self.edges.values()),
            )
            return
        if algorithm == "leiden":
            self._communities = _leiden_schema(
                list(self.nodes.values()),
                list(self.edges.values()),
            )
            return
        raise ValueError(f"graph clustering algorithm is not supported: {algorithm}")

    async def community_schema(self) -> dict[str, Any]:
        """Return community schema generated by ``clustering``."""
        if not self._communities:
            await self.clustering("connected_components")
        return dict(self._communities)


def _leiden_schema(
    nodes: list[GraphNode],
    edges: list[GraphEdge],
) -> dict[str, dict[str, Any]]:
    try:
        import networkx as nx
        from graspologic.partition import hierarchical_leiden
        from graspologic.utils import largest_connected_component
    except ImportError as exc:
        raise ImportError(
            "Leiden graph clustering requires optional dependencies. "
            'Install them with: pip install "heta-framework[graph]"'
        ) from exc

    graph = nx.Graph()
    for node in nodes:
        graph.add_node(node.id, **dict(node.properties))
    for edge in edges:
        graph.add_edge(edge.source_id, edge.target_id, **dict(edge.properties))

    if graph.number_of_nodes() == 0:
        return {}
    if graph.number_of_edges() == 0:
        return _connected_component_schema(nodes, edges)

    stable_graph = _stable_largest_connected_component(graph, largest_connected_component)
    partitions = hierarchical_leiden(stable_graph)
    node_clusters: dict[str, list[dict[str, int]]] = defaultdict(list)
    levels: defaultdict[int, set[int]] = defaultdict(set)
    for partition in partitions:
        level = int(partition.level)
        cluster = int(partition.cluster)
        node_id = str(partition.node)
        node_clusters[node_id].append({"level": level, "cluster": cluster})
        levels[level].add(cluster)

    return _cluster_schema_from_node_clusters(nodes, edges, node_clusters, levels)


def _stable_largest_connected_component(graph: Any, largest_connected_component: Any) -> Any:
    import networkx as nx

    graph = graph.copy()
    graph = largest_connected_component(graph)
    node_mapping = {node: str(node).upper().strip() for node in graph.nodes()}
    graph = nx.relabel_nodes(graph, node_mapping)
    return _stabilize_graph(graph)


def _stabilize_graph(graph: Any) -> Any:
    import networkx as nx

    fixed_graph = nx.DiGraph() if graph.is_directed() else nx.Graph()
    fixed_graph.add_nodes_from(sorted(graph.nodes(data=True), key=lambda item: item[0]))

    graph_edges = list(graph.edges(data=True))
    if not graph.is_directed():
        graph_edges = [
            (target, source, data) if source > target else (source, target, data)
            for source, target, data in graph_edges
        ]
    fixed_graph.add_edges_from(
        sorted(graph_edges, key=lambda item: f"{item[0]} -> {item[1]}")
    )
    return fixed_graph


def _cluster_schema_from_node_clusters(
    nodes: list[GraphNode],
    edges: list[GraphEdge],
    node_clusters: dict[str, list[dict[str, int]]],
    levels: defaultdict[int, set[int]],
) -> dict[str, dict[str, Any]]:
    node_by_id = {node.id: node for node in nodes}
    communities: defaultdict[str, dict[str, Any]] = defaultdict(
        lambda: {
            "level": 0,
            "title": "",
            "nodes": set(),
            "edges": set(),
            "chunk_ids": set(),
            "occurrence": 0.0,
            "sub_communities": [],
        }
    )
    max_chunk_count = 1

    for node_id, clusters in node_clusters.items():
        node_edges = [
            edge
            for edge in edges
            if edge.source_id == node_id or edge.target_id == node_id
        ]
        node = node_by_id.get(node_id)
        for cluster_info in clusters:
            community_id = str(cluster_info["cluster"])
            community = communities[community_id]
            community["level"] = cluster_info["level"]
            community["title"] = f"Cluster {community_id}"
            community["nodes"].add(node_id)
            community["edges"].update(
                tuple(sorted((edge.source_id, edge.target_id))) for edge in node_edges
            )
            if node is not None:
                community["chunk_ids"].update(_community_chunk_ids([node], node_edges))
            max_chunk_count = max(max_chunk_count, len(community["chunk_ids"]))

    ordered_levels = sorted(levels)
    for index, current_level in enumerate(ordered_levels[:-1]):
        next_level = ordered_levels[index + 1]
        for community_id in levels[current_level]:
            current = communities[str(community_id)]
            current_nodes = current["nodes"]
            current["sub_communities"] = [
                str(child_id)
                for child_id in levels[next_level]
                if communities[str(child_id)]["nodes"].issubset(current_nodes)
            ]

    return {
        community_id: {
            "level": data["level"],
            "title": data["title"],
            "nodes": sorted(data["nodes"]),
            "edges": [list(edge) for edge in sorted(data["edges"])],
            "chunk_ids": sorted(data["chunk_ids"]),
            "occurrence": len(data["chunk_ids"]) / max_chunk_count,
            "sub_communities": data["sub_communities"],
        }
        for community_id, data in communities.items()
    }


def _connected_component_schema(
    nodes: list[GraphNode],
    edges: list[GraphEdge],
) -> dict[str, dict[str, Any]]:
    node_ids = sorted(node.id for node in nodes)
    adjacency: dict[str, set[str]] = {node_id: set() for node_id in node_ids}

    for edge in edges:
        adjacency.setdefault(edge.source_id, set()).add(edge.target_id)
        adjacency.setdefault(edge.target_id, set()).add(edge.source_id)

    visited: set[str] = set()
    raw_communities: list[tuple[list[str], list[GraphEdge], list[str]]] = []
    max_chunk_count = 1

    for node_id in sorted(adjacency):
        if node_id in visited:
            continue
        stack = [node_id]
        component: set[str] = set()
        while stack:
            current = stack.pop()
            if current in visited:
                continue
            visited.add(current)
            component.add(current)
            stack.extend(sorted(adjacency.get(current, set()) - visited))

        component_edges = [
            edge
            for edge in edges
            if edge.source_id in component and edge.target_id in component
        ]
        chunk_ids = _community_chunk_ids(
            [node for node in nodes if node.id in component],
            component_edges,
        )
        max_chunk_count = max(max_chunk_count, len(chunk_ids))
        raw_communities.append((sorted(component), component_edges, chunk_ids))

    communities: dict[str, dict[str, Any]] = {}
    for index, (community_nodes, community_edges, chunk_ids) in enumerate(raw_communities):
        community_id = f"community_{index}"
        communities[community_id] = {
            "level": 0,
            "title": f"Community {community_id}",
            "nodes": community_nodes,
            "edges": sorted(
                [list((edge.source_id, edge.target_id)) for edge in community_edges]
            ),
            "chunk_ids": chunk_ids,
            "occurrence": len(chunk_ids) / max_chunk_count,
            "sub_communities": [],
        }
    return communities


def _community_chunk_ids(nodes: list[GraphNode], edges: list[GraphEdge]) -> list[str]:
    values: list[str] = []
    for node in nodes:
        values.extend(_string_values(node.properties.get("source_ids")))
        values.extend(_string_values(node.properties.get("source_id")))
    for edge in edges:
        values.extend(_string_values(edge.properties.get("source_ids")))
        values.extend(_string_values(edge.properties.get("source_id")))
    return sorted(set(values))


def _string_values(value: Any) -> list[str]:
    if value is None:
        return []
    if isinstance(value, str):
        return [item.strip() for item in value.split("<SEP>") if item.strip()]
    if isinstance(value, list | tuple | set):
        return [str(item).strip() for item in value if str(item).strip()]
    return [str(value).strip()]
